# NOTE: Ensure if any passwords or sensitive info is added to use env variables
ecw_connector:
  target: dev
  outputs:
    dev:
      type: sqlserver
      driver: "ODBC Driver 18 for SQL Server"
      server: 127.0.0.1
      port: 1433
      database: ecw_data
      schema: dbo
      user: "{{ env_var('SQL_USER') }}"
      password: "{{ env_var('SQL_PASSWORD') }}"
      encrypt: true
      trust_cert: true
